site_name: "技术博客笔记"

nav:
  - Home: "README.md"
  - Manual:
    - 'start a project': github/start.md
    - github/end.md
    - leetcode/01.md
  - About: about.md

repo_url: https://github.com/echonoshy/gc-hub
site_author: lake.lax
# theme: material

